algo = input('Digite algo')
print('Qual é o tipo desse valor ?',type(algo))
print(algo.isdecimal())
print(algo.isnumeric())
print(algo.isalnum())
print(algo.isdigit())
print(algo.isidentifier())
print(algo.islower())
print(algo.isupper())
